### ISSUE TITLE
Unsupported encoding command ansicpg949

### ISSUE THREAD

**Issue by jams777** [joniles/rtfparserkit#9]
Hi Jon,
thanks for making this code. ^^
I am trying to use it in my project.

but error ~ ㅠㅠ

net.sf.mpxj.mpp.MPPReader called -> read(InputStream is) ~

help~
example file : [error.zip](https://github.com/joniles/rtfparserkit/files/108227/error.zip)

http://stackoverflow.com/questions/35062687/unsupported-encoding-command-ansicpg949

java.lang.IllegalArgumentException: Unsupported encoding command ansicpg949
	at com.rtfparserkit.parser.standard.StandardRtfParser.processEncoding(StandardRtfParser.java:349)
	at com.rtfparserkit.parser.standard.StandardRtfParser.processCommand(StandardRtfParser.java:150)
	at com.rtfparserkit.parser.raw.RawRtfParser.handleCommand(RawRtfParser.java:278)
	at com.rtfparserkit.parser.raw.RawRtfParser.handleCommand(RawRtfParser.java:241)
	at com.rtfparserkit.parser.raw.RawRtfParser.parse(RawRtfParser.java:87)
	at com.rtfparserkit.parser.standard.StandardRtfParser.parse(StandardRtfParser.java:50)
	at com.rtfparserkit.converter.text.AbstractTextConverter.convert(AbstractTextConverter.java:41)
	at com.rtfparserkit.converter.text.StringTextConverter.convert(StringTextConverter.java:34)
	at net.sf.mpxj.common.RtfHelper.strip(RtfHelper.java:61)
	at net.sf.mpxj.mpp.MPP14Reader.processTaskData(MPP14Reader.java:1513)
	at net.sf.mpxj.mpp.MPP14Reader.process(MPP14Reader.java:102)
	at net.sf.mpxj.mpp.MPPReader.read(MPPReader.java:136)
	at net.sf.mpxj.mpp.MPPReader.read(MPPReader.java:79)

**Comment by jams777** [comment]
Fast processing. Thank you.
